---
name: 'Artifacts Setup'
description: 'Set outputs to work with Artifacts Actions'
inputs:
  url:
    description: 'The url of Artifacts'
    required: true
  user:
    description: |
      The user to authenticate with Artifacts.
      Usually setup as a secret in the organization,
      ask your admin for the key name.
    required: true
  password:
    description: |
      The password to authenticate the operation with Artifacts.
    required: true
  method:
    description: |
      What kind of interaction you will perform with Artifacts.
      With the choice of: setup, upload, promote, prolong.
    required: true
  name:
    description: |
      The name of the artifacts build you will use.
      Only used with prolong and promote method
    required: false
    default: 'default'
  tag:
    description: |
      The git tag name of the artifacts you are going to promote.
      To be used with `promote` method.
    required: false
    default: 'default'
  source:
    description: |
      File or directory to upload. To be used with the upload method.
    required: false
    default: '.'
  workflow-name:
    description: |
      Name of the workflow file you want to have the Artifacts name.
    required: false
    default: 'default'
  args:
    description: |
      List of key value pairs to set when indexing metadata on Artifacts
      Example:
      args: |
        key=value
        foo=bar
    required: false
  token:
    description: |
      The GitHub Personal Access Token (PAT)
    default: ${{ github.token }}
    required: false
outputs:
  name:
    description: |
      The name of the artifacts for a specific workflow.
      This name will be unique for the whole workflow and can be
      used by further steps to locate the artifacts inside a job.
    value: ${{ steps.artifacts.outputs.name }}
  link:
    description: |
      The full url in which artifacts will be stored.
    value: ${{ steps.artifacts.outputs.link }}
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
