---
on:
  push:
    tags:
    - '**'

name: promote release

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get the artifacts name of workflow test-get
      uses: ./
      id: artifacts
      with:
        url: https://artifacts.scality.net
        user: ${{ secrets.ARTIFACTS_USER }}
        password: ${{ secrets.ARTIFACTS_PASSWORD }}
        workflow-name: test-get
        method: get

    - name: Artifacts Promote
      uses: ./
      with:
        url: https://artifacts.scality.net
        user: ${{ secrets.ARTIFACTS_USER }}
        password: ${{ secrets.ARTIFACTS_PASSWORD }}
        name: ${{ steps.artifacts.outputs.name }}
        tag: '${{ github.ref_name }}'
        method: promote
