---

on:
  push: {}
  workflow_dispatch: {}

name: share artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifacts-name: ${{ steps.artifacts.outputs.name }}
      artifacts-link: ${{ steps.artifacts.outputs.link }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: artifacts upload
      id: artifacts
      uses: ./
      with:
        url: https://artifacts.scality.net
        user: ${{ secrets.ARTIFACTS_USER }}
        password: ${{ secrets.ARTIFACTS_PASSWORD }}
        source: action.yaml
        method: upload

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Retrieve file
      run: |
        curl -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }} ${{ needs.build.outputs.artifacts-link }}/action.yaml -o /tmp/action.yaml
    - name: Show file content
      run: cat /tmp/action.yaml
