---
name: 'Test errors'

on:
  push: {}
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: production

jobs:
  file-does-not-exist:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v3
      - name: Push all files
        id: artifacts-test
        continue-on-error: true
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: ./test-files
          method: upload
      - name: verify error
        if: steps.artifacts-test.outcome == 'success'
        run: /bin/false

  wrong-password:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v3
      - name: Push all files
        id: artifacts-test
        continue-on-error: true
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: 'wrong-password'
          source: action.yaml
          method: upload
      - name: verify error
        if: steps.artifacts-test.outcome == 'success'
        run: /bin/false

  wrong-host:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push all files
        id: artifacts-test
        continue-on-error: true
        uses: ./
        with:
          url: http://localhost:4242
          user: toto
          password: 'wrong-password'
          source: action.yaml
          method: upload
      - name: verify error
        if: steps.artifacts-test.outcome == 'success'
        run: /bin/false
