---
name: test-setup

on: push

jobs:
  test-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Artifacts Setup
        id: artifacts-setup
        uses: ./
        with:
          url: https://artifacts.scality.net
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          method: setup
      - name: Print the artifacts name
        run: echo ${{ steps.artifacts-setup.outputs.name }}
