name: 'build-test'

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INPUT_URL: http://localhost:8080
      INPUT_USER: ${{ secrets.ARTIFACTS_USER }}
      INPUT_PASSWORD: ${{ secrets.ARTIFACTS_PASSWORD }}
    services:
      cloudserver-front:
        image: "zenko/cloudserver:8.1.2"
        env:
          REMOTE_MANAGEMENT_DISABLE: 1
          LOG_LEVEL: debug
          ENDPOINT: "cloudserver-front"
          CI: false
        ports:
        - 8000:8000
      artifacts:
        image: "registry.scality.com/artifacts/artifacts:4.2.6"
        ports:
          - 8080:80
        env:
          AWS_SECRET_ACCESS_KEY: verySecretKey1
          AWS_ACCESS_KEY_ID: accessKey1
          AWS_BUCKET_PREFIX: artifacts
          ENDPOINT_URL: http://cloudserver-front:8000
          AWS_XML_NS: http://s3.amazonaws.com/doc/2006-03-01/
          GITHUB_API_COMPANY: scality
          GITHUB_API_ENABLED: true
          GITHUB_USER_ALLOWED_UPLOAD: ${{ secrets.ARTIFACTS_USER }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 16.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 16.x
      - name: Waiting for cloudserver to boot
        run: |
          ret=0
          while [[ $ret != "200" ]]; do
            echo Waiting for cloudserver
            ret=$(docker exec ${{ job.services.cloudserver-front.id }} curl -s -o /dev/null -L -w ''%{http_code}'' http://localhost:8000/_/healthcheck/deep)
            sleep 5
          done
      - name: Setup bucket
        run: |
          aws s3 --endpoint=http://localhost:8000 mb s3://artifacts-staging --region us-east-1
          aws s3 --endpoint=http://localhost:8000 mb s3://artifacts-promoted --region us-east-1
          aws s3 --endpoint=http://localhost:8000 mb s3://artifacts-prolonged --region us-east-1
        env:
          AWS_SECRET_ACCESS_KEY: verySecretKey1
          AWS_ACCESS_KEY_ID: accessKey1
      - name: curl artifacts
        run: |
          curl -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }} http://localhost:8080/builds/
      - run: |
          yarn install
      - run: |
          yarn run all
