---
name: test-setup

on:
  push: {}
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: production

jobs:
  test-setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v4
      - name: Artifacts Setup
        id: artifacts-setup
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          method: setup
      - name: Print the artifacts name
        run: echo ${{ steps.artifacts-setup.outputs.name }}
