
concurrency:
  group: 'load-tests-${{ github.ref }}'
  cancel-in-progress: false

on:
  push:
    branches:
      - development/**
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: production

name: test-load

jobs:
  load-test:
    strategy:
      fail-fast: false
      matrix:
        test:
        - host: ubuntu-latest
          name: github-hosted
        - host: ubuntu-latest
          name: github-hosted-container
          container: ubuntu
        - host: [self-hosted, focal, large]
          name: self-hosted
    runs-on: ${{ matrix.test.host }}
    environment: ${{ inputs.environment || 'production' }}
    container: ${{ matrix.test.container }}
    name: load tests on ${{ matrix.test.name }}
    steps:
      - uses: actions/checkout@v4
      - name: create multiple files
        run: |
          mkdir -p artifacts/${{ matrix.test.name }}
          for i in {1..20}; do
            head -c 1G /dev/urandom > artifacts/${{ matrix.test.name }}/$i.txt
          done
        shell: bash
      - name: Push all files
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: ./artifacts
          method: upload
