---
name: test-get

on:
  push: {}
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        default: production

jobs:
  upload:
    environment: ${{ inputs.environment || 'production' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo -n "SUCCESSFUL" > .final_status
      - name: Artifacts Upload
        id: artifacts-upload
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          source: .final_status
          method: upload
      - name: Download file to update artifacts cache
        run: |
          curl -H 'ForceCacheUpdate: yes' \
            -u ${{ secrets.ARTIFACTS_USER }}:${{ secrets.ARTIFACTS_PASSWORD }}  \
            --silent --fail --show-error \
            --max-time 3600 \
            ${{ vars.ARTIFACTS_URL }}/download/${{ steps.artifacts-upload.outputs.name }}/.final_status
  test-get-container:
    needs:
      - upload
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    container:
      image: 'ubuntu:20.04'
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: apt-get update
      - run: apt-get install -y curl
      - name: Get Artifacts
        id: artifacts-get
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          workflow-name: test-get
          method: get
      - name: Print the artifacts name
        run: |
          echo ${{ steps.artifacts-get.outputs.name }}
          echo ${{ steps.artifacts-get.outputs.link }}

  test-get:
    needs:
      - upload
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'production' }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Artifacts
        id: artifacts-get
        uses: ./
        with:
          url: ${{ vars.ARTIFACTS_URL }}
          user: ${{ secrets.ARTIFACTS_USER }}
          password: ${{ secrets.ARTIFACTS_PASSWORD }}
          workflow-name: test-get
          method: get
      - name: Print the artifacts name
        run: |
          echo ${{ steps.artifacts-get.outputs.name }}
          echo ${{ steps.artifacts-get.outputs.link }}
